---
# The time (in seconds) to wait after the last event was received before handling
delayInSeconds: 1

mimeDirectories:
  - /usr/share/mime
  - ~/.local/share/mime

# Cleanup zero byte files automatically
cleanupZeroByte: true

paths:
  - path: ~/Descargas
    processors:
      - type: image
        handler: move
        path: ~/Im치genes/input
      - type: application/gzip
        handler: extract
        path: ~/test/{{.date}}
        properties:
          chown: mproffitt:admin
          chmod: u+rw,g=u-w,o=
      - type: application/x-executable
        handler: install
        path: ~/bin
        properties:
          lowercase-destination: true
          strip-extension: true
  - path: ~/Im치genes/input
    processors:
      - type: image/x-xcf
        handler: move
        path: ~/Im치genes/workbench/xcf
      - type: image/x-dcraw
        handler: move
        path: ~/Im치genes/workbench/{{.ucext}}/{{.date}}
      - type: "*"
        handler: move
        path: ~/Descargas

pluginDirectory: plugins

logLevel: info

bufferSize: 50
