---
# The time (in seconds) to wait after the last event was received before handling
delayInSeconds: 5

# Cleanup zero byte files automatically
cleanupZeroByte: true

# The set of locations on disk to watch
watch:
  - ~/Descargas
  - ~/Imágenes/input

processors:
  - type: image/x-xcf
    handler: move
    path: ~/Imágenes/workbench/xcf
  - type: application/gzip
    handler: extract
    path: ~/test/{{.date}}
  - type: application/x-executable
    handler: install
    path: /home/mproffitt/bin
    properties:
      lowercase-destination: true
      strip-extension: true
  - type: image/x-dcraw
    handler: move
    path: ~/Imágenes/workbench/{{.ucext}}/{{.date}}
